name: Build

on: [pull_request, push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenCL
        run: |
          sudo add-apt-repository ppa:intel-opencl/intel-opencl
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@aabbfeb
      - uses: actions-rs/toolchain@b2417cd
        with:
          toolchain: stable
      - name: Build
        run: cargo build
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenCL
        run: |
          sudo add-apt-repository ppa:intel-opencl/intel-opencl
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@aabbfeb
      - uses: actions-rs/toolchain@b2417cd
        with:
          toolchain: stable
      - name: Build release
        run: cargo build --release